config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :books
  resources :users

  get 'home/about' => 'homes#about', as:'about'
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }
  
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :ensure_user, only: [:edit, :update, :destroy]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice]="You have created book successfully."
    else
    @books = Book.all
    @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @books = Book.new

  end

  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice]="You have updated book successfully."
    else
      render :edit
      flash[:notice]="You have created book successfully."
    end  
  end

  private

  def ensure_user
    @book = Book.find(params[:id])
      unless @book.user == current_user
        redirect_to books_path
      end
  end


  def book_params
    params.require(:book).permit(:title, :image, :body, :opinion)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<!-- ユーザーの詳細 -->

      <h2>New book</h2>
        <%= form_with model: book do |f| %>
          <label for="book_title",>Title</label></br>
            <%= f.text_field :title, class:"form-control" %></br>
          <label>Opinion</label></br>
            <%= f.text_area :body, class:"form-control"  %></br>
          <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>
    

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
       <% if @book.errors.any? %>
        <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        </ul>
      <% end %>
  		<%= form_with model: @book do |f| %>
  		<div class="form-group">
        <label for="inputTitle">Title</label></br>
        <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"title", class:"form-control" %></br>
        <label for="inputOpinion">Opinion</label></br>
        <%= f.text_area :body, autofocus: true, id:"inputOpinion", placeholder:"opinion", class:"form-control" %></br>
        <%= f.submit "Update Book", class:"btn btn-success" %></br>
        <%= link_to "Show", book_path(@book.id) %> |
        <%= link_to "Back",  books_path %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0" >
  <% if @book.errors.any? %>
  <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row">
   <div class="col-md-3">
    <%= render 'users/userinfo', user: @user %>
    <%= render 'list', book: @book %>
    </div>


    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <th>
              <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            </th>
            <th>
              <%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
            </th>
            <th>
              <p><%= book.body %></p>
            </th>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<!--<h1>投稿フォーム</h1>-->
<!--  <%= form_with model: @book do |f| %>-->
<!--    <h4>画像</h4>-->
<!--      <%= f.file_field :image, accept: "image/*" %>-->
<!--    <h4>title</h4>-->
<!--      <%= f.text_field :title %>-->
<!--    <h4>body</h4>-->
<!--      <%= f.text_area :body %>-->
<!--    <%= f.submit '投稿' %>-->
<!--  <% end %>-->

app/views/books/show.html.erb
<div class="container px-5 px-sm-0" >
  <div class="row">
   <div class="col-md-3">
     <%= render 'users/userinfo', user: @user %>
     <%= render 'list', book: @books %>
   </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <th>
              <%= link_to user_path(@book.user.id) do %>
                <%= image_tag @book.user.get_profile_image(100,100) %></br>
                <%= @book.user.name %>
              <% end %>
           </th>
            <th>
              <%= @book.title %>
            </th>
            <th>
              <%= @book.body %>
            </th>
            <% if @book.user == current_user %>
            <th>
            <%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success edit_book_83230" %>
            </th>
            <th>
            <%= link_to "Destroy", book_path(@book), method: :delete, class:"btn btn-sm btn-danger destroy_book" %>
            </th>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>