config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :books
  resources :users

  get 'home/about' => 'homes#about', as:'about'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path, class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <% if user_signed_in? %>
            <ul class="navbar-nav ml-auto">
              <li>
                <%= link_to user_path(current_user.id), class:"nav-link text-light" do %>
                <i class="fas fa-home"></i>
                Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path, class:"nav-link text-light" do %>
                <i class="fas fa-users"></i>
                Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path, class:"nav-link text-light" do %>
                <i class="fas fa-book-open"></i>
                Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
                <i class="fas fa-sign-out-alt"></i>
                Log out
                <% end %>
              </li>
            </ul>

            <% else %>
              <ul class="navbar-nav ml-auto">
              <li>
                <%= link_to root_path, class:"nav-link text-light" do %>
                <i class="fas fa-home"></i>
                Home
                <% end %>
              </li>
              <li>
                <%= link_to about_path, class:"nav-link text-light" do %>
                <i class="fas fa-link"></i>
                About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                <i class="fas fa-user-plus"></i>
                Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class:"nav-link text-light" do %>
                <i class="fas fa-sign-in-alt"></i>
                Log in
                <% end %>
              </li>
            </ul>
            <% end %>
          </div>
        </div>
      </nav>

    </header>




      <div class="flash-notifications">
        <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: key) %>
        <% end %>
      </div>

    <%= yield %>

  </body>

  <footer>
    <div class="container mt-5">
    	<div class="row">
      	<div class="mx-auto">
      		<p>CopyRight Infratop.inc</p>
      	</div>
      </div>
    </div>
  </footer>

</html>